
import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import CarbonCalculator from '@/components/CarbonCalculator';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Info } from 'lucide-react';

const CalculatorPage = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 container mx-auto px-4 py-8">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold text-eco-forest">Calculate Your Carbon Footprint</h1>
          <p className="text-muted-foreground mt-2">
            Measure your environmental impact and discover how you can offset it with carbon credits
          </p>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <CarbonCalculator />
          </div>
          
          <div className="space-y-6">
            <Card className="shadow-md border-eco-blue-light">
              <CardHeader>
                <CardTitle className="flex items-center text-xl text-eco-forest">
                  <Info className="h-5 w-5 mr-2" />
                  Why Calculate?
                </CardTitle>
                <CardDescription>
                  Understanding your carbon footprint is the first step to reducing it
                </CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground mb-4">
                  Your carbon footprint is the total amount of greenhouse gases generated by your actions. By measuring it, you can:
                </p>
                <ul className="list-disc pl-5 space-y-2 text-sm">
                  <li>Identify high-impact areas of your lifestyle</li>
                  <li>Track your progress in reducing emissions</li>
                  <li>Earn carbon credits for eco-friendly actions</li>
                  <li>Offset your unavoidable emissions</li>
                </ul>
              </CardContent>
            </Card>
            
            <Card className="shadow-md border-eco-green">
              <CardHeader>
                <CardTitle className="text-xl text-eco-forest">What's Next?</CardTitle>
                <CardDescription>
                  After calculating your footprint
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3 text-sm">
                  <li className="flex items-start">
                    <span className="bg-eco-green text-white rounded-full h-5 w-5 flex items-center justify-center mr-2 mt-0.5 text-xs">1</span>
                    <span>Connect your wallet on the dashboard</span>
                  </li>
                  <li className="flex items-start">
                    <span className="bg-eco-green text-white rounded-full h-5 w-5 flex items-center justify-center mr-2 mt-0.5 text-xs">2</span>
                    <span>Convert your calculations to carbon credits</span>
                  </li>
                  <li className="flex items-start">
                    <span className="bg-eco-green text-white rounded-full h-5 w-5 flex items-center justify-center mr-2 mt-0.5 text-xs">3</span>
                    <span>Trade or redeem credits in the marketplace</span>
                  </li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default CalculatorPage;
