// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqoqozhbxvfodvfzdhmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxb3FvemhieHZmb2R2ZnpkaG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjE0NzUsImV4cCI6MjA2MTM5NzQ3NX0.3cJW-XA-pPifL_9KBVVgNJghp7rKv9QrYNtT9X3wWec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);